<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('languages')->delete();
        
        \DB::table('languages')->insert(array (
            0 => 
            array (
                'id' => 1,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_name',
                'lang_tag' => 'en',
                'lang_content' => 'Fresns',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_desc',
                'lang_tag' => 'en',
                'lang_content' => 'Fresns is a free and open source social network service software, a general-purpose community product designed for cross-platform, and supports flexible and diverse content forms. It conforms to the trend of the times, satisfies a variety of operating scenarios, is more open and easier to re-development.',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name',
                'lang_tag' => 'en',
                'lang_content' => 'User',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_id_name',
                'lang_tag' => 'en',
                'lang_content' => 'UID',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name_name',
                'lang_tag' => 'en',
                'lang_content' => 'Username',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_nickname_name',
                'lang_tag' => 'en',
                'lang_content' => 'Nickname',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_role_name',
                'lang_tag' => 'en',
                'lang_content' => 'Userrole',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'group_name',
                'lang_tag' => 'en',
                'lang_content' => 'Group',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'hashtag_name',
                'lang_tag' => 'en',
                'lang_content' => 'Hashtag',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'post_name',
                'lang_tag' => 'en',
                'lang_content' => 'Post',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'comment_name',
                'lang_tag' => 'en',
                'lang_content' => 'Comment',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_post_name',
                'lang_tag' => 'en',
                'lang_content' => 'Create Post',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_comment_name',
                'lang_tag' => 'en',
                'lang_content' => 'Reply',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_member_name',
                'lang_tag' => 'en',
                'lang_content' => 'Like',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_group_name',
                'lang_tag' => 'en',
                'lang_content' => 'Like',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_hashtag_name',
                'lang_tag' => 'en',
                'lang_content' => 'Like',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_post_name',
                'lang_tag' => 'en',
                'lang_content' => 'Like',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_comment_name',
                'lang_tag' => 'en',
                'lang_content' => 'Like',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_member_name',
                'lang_tag' => 'en',
                'lang_content' => 'Follow',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_group_name',
                'lang_tag' => 'en',
                'lang_content' => 'Join',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_hashtag_name',
                'lang_tag' => 'en',
                'lang_content' => 'Watching',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_post_name',
                'lang_tag' => 'en',
                'lang_content' => 'Save post',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_comment_name',
                'lang_tag' => 'en',
                'lang_content' => 'Save comment',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_member_name',
                'lang_tag' => 'en',
                'lang_content' => 'Block',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_group_name',
                'lang_tag' => 'en',
                'lang_content' => 'Block',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_hashtag_name',
                'lang_tag' => 'en',
                'lang_content' => 'Block',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_post_name',
                'lang_tag' => 'en',
                'lang_content' => 'Hide post',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_comment_name',
                'lang_tag' => 'en',
                'lang_content' => 'Hide comment',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Administrator',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Interdiction',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Pending Review',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'General User',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'All',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Text',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Images',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Videos',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 5,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Audios',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 6,
                'table_key' => NULL,
                'lang_tag' => 'en',
                'lang_content' => 'Docs',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => 'Fresns 中文网',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_desc',
                'lang_tag' => 'zh-Hans',
                'lang_content' => 'Fresns 是一款免费开源的社交网络服务软件，专为跨平台而打造的通用型社区产品，支持灵活多样的内容形态，可以满足多种运营场景，符合时代潮流，更开放且更易于二次开发。',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '用户',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_id_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '用户号',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '用户名',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_nickname_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '昵称',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_role_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '角色',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'group_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '小组',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'hashtag_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '话题',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'post_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '帖子',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'comment_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '评论',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_post_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '发帖',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_comment_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '回复',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_member_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '喜欢',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_group_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '赞',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_hashtag_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '赞',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_post_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '赞',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_comment_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '赞',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_member_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '关注',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_group_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '加入',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_hashtag_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '订阅',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_post_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '收藏',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_comment_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '收藏',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_member_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '拉黑',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_group_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '屏蔽',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_hashtag_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '不感兴趣',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_post_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '不想看到',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_comment_name',
                'lang_tag' => 'zh-Hans',
                'lang_content' => '不想看到',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '管理员',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '禁言中',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '待审核',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '普通会员',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '不限',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '文本',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '图片',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '视频',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 5,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '音频',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 6,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hans',
                'lang_content' => '文件',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => 'Fresns 中文網',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'site_desc',
                'lang_tag' => 'zh-Hant',
                'lang_content' => 'Fresns 是一款免費開源的社交網絡服務軟件，專為跨平台而打造的通用型社區產品，支持靈活多樣的內容形態，可以滿足多種運營場景，符合時代潮流，更開放且更易於二次開發。',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '用戶',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_id_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '用戶號',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_name_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '用戶名',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_nickname_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '暱稱',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'member_role_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '角色',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'group_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '小組',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'hashtag_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '話題',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'post_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '帖子',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'comment_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '評論',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_post_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '發帖',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'publish_comment_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '回复',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_member_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '喜歡',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_group_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '贊',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_hashtag_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '贊',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_post_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '贊',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'like_comment_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '贊',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_member_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '關注',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_group_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '加入',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_hashtag_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '訂閱',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_post_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '收藏',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'follow_comment_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '收藏',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_member_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '拉黑',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_group_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '屏蔽',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_hashtag_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '不感興趣',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_post_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '不想看到',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'table_name' => 'configs',
                'table_field' => 'item_value',
                'table_id' => NULL,
                'table_key' => 'shield_comment_name',
                'lang_tag' => 'zh-Hant',
                'lang_content' => '不想看到',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '管理員',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '禁言中',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '待審核',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'table_name' => 'member_roles',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '普通會員',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 1,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '不限',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 2,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '文本',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 3,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '圖片',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 4,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '視頻',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 5,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '音頻',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'table_name' => 'plugin_usages',
                'table_field' => 'name',
                'table_id' => 6,
                'table_key' => NULL,
                'lang_tag' => 'zh-Hant',
                'lang_content' => '文檔',
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => NULL,
            ),
        ));

    }
}