<?php

/*
 * Fresns (https://fresns.org)
 * Copyright (C) 2021-Present Jarvis Tang
 * Released under the Apache-2.0 License.
 */

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PluginsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('plugins')->delete();

        \DB::table('plugins')->insert([
            0 => [
                'id' => 1,
                'type' => 3,
                'unikey' => 'FresnsEngine',
                'name' => 'Fresns 网站引擎',
                'description' => 'Fresns 官方开发的网站引擎，集成在主程序中运行。',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => '["apiKey"]',
                'plugin_domain' => null,
                'access_path' => '/',
                'settings_path' => '/fresnsengine/settings/general',
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'type' => 4,
                'unikey' => 'ThemeFrame',
                'name' => 'Fresns 主题框架',
                'description' => 'Fresns 官方开发的主题框架，展示网站端功能和交互流程。',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'type' => 1,
                'unikey' => 'FresnsEmail',
                'name' => 'Fresns Email',
                'description' => 'Fresns 官方开发的 SMTP 发信方式的邮件插件。',
                'version' => '1.2.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => '["sendEmail"]',
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => '/fresns-email/settings',
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'type' => 1,
                'unikey' => 'EasySms',
                'name' => 'Easy SMS',
                'description' => 'Fresns 官方开发的支持多家服务商的短信插件。',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => '["sendSms"]',
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => '/easy-sms/setting',
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'type' => 1,
                'unikey' => 'CmdWordTool',
                'name' => '命令字测试工具',
                'description' => 'Fresns 官方开发的命令字测试工具',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'type' => 1,
                'unikey' => 'HelperTool',
                'name' => '辅助函数测试工具',
                'description' => 'Fresns 官方开发的辅助函数测试工具',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'type' => 1,
                'unikey' => 'Placeholder',
                'name' => 'Fresns 占位插件',
                'description' => '占位插件，用于测试和查看客户端生成的参数。',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.cn',
                'scene' => '["apiKey","register","join","sendEmail","sendSms","sendIos","sendAndroid","sendWechat","connect","prove","multiple","recharge","withdraw","storage","map","editor","followGroup","expandEditor","expandContentType","expandData","expandManage","expandGroup","expandUser"]',
                'plugin_domain' => null,
                'access_path' => '/placeholder/index?uuid={uuid}&sign={sign}&lang={langTag}&type={type}&scene={scene}&aid={aid}&uid={uid}&rid={rid}&gid={gid}&pid={pid}&cid={cid}&eid={eid}&fid={fid}&plid={plid}&clid={clid}&uploadToken={uploadToken}&uploadInfo={uploadInfo}',
                'settings_path' => null,
                'theme_functions' => 0,
                'install_code' => null,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
        ]);
    }
}
