<?php

/*
 * Fresns (https://fresns.org)
 * Copyright (C) 2021-Present Jarvis Tang
 * Released under the Apache-2.0 License.
 */

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PluginsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('plugins')->delete();

        \DB::table('plugins')->insert([
            0 => [
                'id' => 1,
                'type' => 3,
                'unikey' => 'FresnsEngine',
                'name' => 'Fresns Web Engine',
                'description' => 'Fresns officially developed website engine, integrated to run in the main application.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => '["apiKey"]',
                'plugin_domain' => null,
                'access_path' => '/',
                'settings_path' => '/fresnsengine/settings/general',
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            1 => [
                'id' => 2,
                'type' => 4,
                'unikey' => 'ThemeFrame',
                'name' => 'Fresns Theme Frame',
                'description' => 'Fresns official development of the theme framework to demonstrate the site side functionality and interaction processes.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            2 => [
                'id' => 3,
                'type' => 1,
                'unikey' => 'FresnsEmail',
                'name' => 'Fresns Email',
                'description' => 'Fresns official development of the SMTP sending method of mail plugin.',
                'version' => '1.2.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => '["sendEmail"]',
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => '/fresns-email/settings',
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            3 => [
                'id' => 4,
                'type' => 1,
                'unikey' => 'EasySms',
                'name' => 'Easy SMS',
                'description' => 'Fresns official development for the Chinese market to support multiple service providers SMS plugin.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => '["sendSms"]',
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => '/easy-sms/setting',
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            4 => [
                'id' => 5,
                'type' => 1,
                'unikey' => 'CmdWordTool',
                'name' => 'CmdWord Test Tool',
                'description' => 'Fresns official helper function test tool.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            5 => [
                'id' => 6,
                'type' => 1,
                'unikey' => 'HelperTool',
                'name' => 'Helper Test Tool',
                'description' => 'Fresns official helper function test tool.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => null,
                'plugin_domain' => null,
                'access_path' => null,
                'settings_path' => null,
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
            6 => [
                'id' => 7,
                'type' => 1,
                'unikey' => 'Placeholder',
                'name' => 'Fresns Placeholder',
                'description' => 'Placeholder plugin for testing and viewing client generated parameters.',
                'version' => '1.0.0',
                'author' => 'Fresns',
                'author_link' => 'https://fresns.org',
                'scene' => '["apiKey","register","join","sendEmail","sendSms","sendIos","sendAndroid","sendWechat","connect","prove","multiple","recharge","withdraw","storage","map","editor","followGroup","expandEditor","expandContentType","expandData","expandManage","expandGroup","expandUser"]',
                'plugin_domain' => null,
                'access_path' => '/placeholder/index?uuid={uuid}&sign={sign}&lang={langTag}&type={type}&scene={scene}&aid={aid}&uid={uid}&rid={rid}&gid={gid}&pid={pid}&cid={cid}&eid={eid}&fid={fid}&plid={plid}&clid={clid}&uploadToken={uploadToken}&uploadInfo={uploadInfo}',
                'settings_path' => null,
                'theme_functions' => 0,
                'is_upgrade' => 0,
                'upgrade_version' => null,
                'upgrade_code' => null,
                'is_enable' => 1,
                'created_at' => '2021-10-08 10:00:00',
                'updated_at' => '2021-10-08 10:00:00',
                'deleted_at' => null,
            ],
        ]);
    }
}
